raw_schema: raw
ref_schema: ref
archive_schema: archive
table_name: pop
path_raw: //phdata01/DROF_DATA/DOH DATA/POP/data/raw
path_tmp: C:/temp/pop
index_type: ccs
index_name: idx_ccs_ref_pop
geo_type:
  block: blk
  blockgroup: blkg
  county: cou
  legdist: lgd
  schooldist: scd
  state: ste
  tract: trc
  zipcode: zip
geo_scope:
  blk: kps
  blkg: kps
  cou: 
  lgd: 
  scd: 
  ste: 
  trc: 
  zip: wa