schema_name: ref
table_name: pop_qa
vars:
  geo_type: VARCHAR(5)
  geo_scope: VARCHAR(4)
  geo_year: VARCHAR(4)
  r_type: SMALLINT
  year: VARCHAR(4)
  col: VARCHAR(10)
  val: SMALLINT
  pop: FLOAT
cols:
  age: age
  age_5: age_5
  age_11: age_11
  age_20: age_20
  gender: gender
  race_wht: race_wht
  race_blk: race_blk
  race_aian: race_aian
  race_as: race_as
  race_nhpi: race_nhpi
  race_hisp: race_hisp
  county: fips_co
