schema_name: ref
table_name: pop_qa
vars:
  geo_type: VARCHAR(5)
  geo_scope: VARCHAR(4)
  geo_year: VARCHAR(4)
  r_type: SMALLINT
  year: VARCHAR(4)
  col: VARCHAR(10)
  val: SMALLINT
  pop: FLOAT
cols:
  age: age
  age5: age5
  age11: age11
  age20: age20
  gender: s
  race_eth: r2_4
  county: fips_co
