schema_name: raw
table_name: pop
field_term: ","
row_term: \n
vars:
  etl_batch_id: INTEGER
  year: VARCHAR(4)
  geo_id: VARCHAR(15)
  racemars: VARCHAR(15)
  gender: VARCHAR(1)
  agestr: VARCHAR(7)
  hispanic: VARCHAR(1)
  pop: FLOAT
  geo_type: VARCHAR(5)
  geo_scope: VARCHAR(4)
  geo_year: VARCHAR(4)
  r_type: SMALLINT
  age: INTEGER
  age11: SMALLINT
  age20: SMALLINT
  s: SMALLINT
  h: SMALLINT
  r1_3: SMALLINT
  r2_4: SMALLINT
  rcode: SMALLINT
  fips_co: SMALLINT