vars:
  etl_batch_ID: INTEGER
  geo_type: VARCHAR(5)
  geo_scope: VARCHAR(4)
  geo_year: VARCHAR(4)
  census_year: VARCHAR(4)
  year: VARCHAR(4)
  r_type: SMALLINT
  geo_id: VARCHAR(15)
  age: SMALLINT
  age_5: SMALLINT
  age_11: SMALLINT
  age_20: SMALLINT
  age_100: SMALLINT
  gender: SMALLINT
  pop: FLOAT
  race_wht: BIT
  race_blk: BIT
  race_aian: BIT
  race_as: BIT
  race_nhpi: BIT
  race_hisp: BIT
  rcode: SMALLINT
  r1r3: SMALLINT
  r2r4: SMALLINT
  fips_co: SMALLINT
  raw_agestr: VARCHAR(7)
  raw_gender: VARCHAR(1)
  raw_racemars: VARCHAR(15)
  raw_hispanic: VARCHAR(1)
